-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 22:13:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ccambpla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccambpla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccambpla` DEFAULT CHARACTER SET utf8 ;
USE `ccambpla` ;

-- -----------------------------------------------------
-- Table `ccambpla`.`tab_tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_tip` (
  `ident_tip` INT NOT NULL AUTO_INCREMENT,
  `nombr_tip` VARCHAR(45) NULL,
  PRIMARY KEY (`ident_tip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_jef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_jef` (
  `ident_jef` INT NOT NULL AUTO_INCREMENT,
  `cedul_jef` INT(11) NULL,
  `nombr_jef` VARCHAR(45) NULL,
  `apeli_jef` VARCHAR(45) NULL,
  `fecna_jef` DATE NULL,
  `telem_jef` VARCHAR(45) NULL,
  `telec_jef` VARCHAR(45) NULL,
  `email_jef` VARCHAR(45) NULL,
  `calle_jef` VARCHAR(45) NULL,
  `direc_jef` VARCHAR(200) NULL,
  `tibom_jef` VARCHAR(45) NULL,
  `seria_jef` VARCHAR(45) NULL,
  `usuar_jef` VARCHAR(45) NULL,
  `contr_jef` VARCHAR(45) NULL,
  `statu_jef` CHAR(1) NULL,
  `ident_tip` INT NOT NULL,
  PRIMARY KEY (`ident_jef`),
  INDEX `fk_tab_jef_tab_tip1_idx` (`ident_tip` ASC),
  CONSTRAINT `fk_tab_jef_tab_tip1`
    FOREIGN KEY (`ident_tip`)
    REFERENCES `ccambpla`.`tab_tip` (`ident_tip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_per`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_per` (
  `ident_per` INT NOT NULL AUTO_INCREMENT,
  `cedul_per` INT(11) NULL,
  `nombr_per` VARCHAR(45) NULL,
  `apeli_per` VARCHAR(45) NULL,
  `fecna_per` DATE NULL,
  `telem_per` VARCHAR(45) NULL,
  `telec_per` VARCHAR(45) NULL,
  `email_per` VARCHAR(45) NULL,
  `calle_per` VARCHAR(45) NULL,
  `direc_per` VARCHAR(200) NULL,
  `tifam_per` VARCHAR(45) NULL,
  `tibom_per` VARCHAR(45) NULL,
  `seria_per` VARCHAR(45) NULL,
  `statu_per` CHAR(1) NULL,
  `ident_tip` INT NOT NULL,
  `ident_jef` INT NOT NULL,
  PRIMARY KEY (`ident_per`),
  INDEX `fk_tab_per_tab_tip1_idx` (`ident_tip` ASC),
  INDEX `fk_tab_per_tab_jef1_idx` (`ident_jef` ASC),
  CONSTRAINT `fk_tab_per_tab_tip1`
    FOREIGN KEY (`ident_tip`)
    REFERENCES `ccambpla`.`tab_tip` (`ident_tip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_per_tab_jef1`
    FOREIGN KEY (`ident_jef`)
    REFERENCES `ccambpla`.`tab_jef` (`ident_jef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_not`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_not` (
  `ident_not` INT NOT NULL AUTO_INCREMENT,
  `titul_not` VARCHAR(100) NULL,
  `desco_not` VARCHAR(100) NULL,
  `descr_not` VARCHAR(2000) NULL,
  `image_not` VARCHAR(250) NULL,
  `fecpu_not` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `statu_not` VARCHAR(45) NULL,
  PRIMARY KEY (`ident_not`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_reg` (
  `ident_reg` INT NOT NULL AUTO_INCREMENT,
  `nombr_reg` VARCHAR(45) NULL,
  `descr_reg` VARCHAR(250) NULL,
  `fecre_reg` DATE NULL,
  `statu_reg` CHAR(1) NULL,
  PRIMARY KEY (`ident_reg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`det_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`det_reg` (
  `correlativo` INT NOT NULL AUTO_INCREMENT,
  `ident_reg` INT NOT NULL,
  `ident_jef` INT NOT NULL,
  PRIMARY KEY (`correlativo`),
  INDEX `fk_det_reg_tab_jef1_idx` (`ident_jef` ASC),
  INDEX `fk_det_reg_tab_reg1_idx` (`ident_reg` ASC),
  CONSTRAINT `fk_det_reg_tab_jef1`
    FOREIGN KEY (`ident_jef`)
    REFERENCES `ccambpla`.`tab_jef` (`ident_jef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_det_reg_tab_reg1`
    FOREIGN KEY (`ident_reg`)
    REFERENCES `ccambpla`.`tab_reg` (`ident_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`det_tem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`det_tem` (
  `correlativo` INT NOT NULL,
  `token_user` VARCHAR(45) NULL,
  `ident_jef` INT NOT NULL,
  PRIMARY KEY (`correlativo`),
  INDEX `fk_det_tem_tab_jef1_idx` (`ident_jef` ASC),
  CONSTRAINT `fk_det_tem_tab_jef1`
    FOREIGN KEY (`ident_jef`)
    REFERENCES `ccambpla`.`tab_jef` (`ident_jef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ccambpla`.`tab_tip`
-- -----------------------------------------------------
START TRANSACTION;
USE `ccambpla`;
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (1, 'ADMINISTRADOR');
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (2, 'VOCERO');
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (3, 'JEFE DE CALLE');
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (4, 'CIUDADANO');

COMMIT;

