-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 21:04:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ccambpla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccambpla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccambpla` DEFAULT CHARACTER SET utf8 ;
USE `ccambpla` ;

-- -----------------------------------------------------
-- Table `ccambpla`.`tab_tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_tip` (
  `ident_tip` INT NOT NULL AUTO_INCREMENT,
  `nombr_tip` VARCHAR(45) NULL,
  PRIMARY KEY (`ident_tip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_fam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_fam` (
  `ident_fam` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ident_fam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_per`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_per` (
  `ident_per` INT NOT NULL AUTO_INCREMENT,
  `cedul_per` INT(11) NULL,
  `nombr_per` VARCHAR(45) NULL,
  `apeli_per` VARCHAR(45) NULL,
  `fecna_per` DATE NULL,
  `telem_per` VARCHAR(45) NULL,
  `telec_per` VARCHAR(45) NULL,
  `email_per` VARCHAR(45) NULL,
  `direc_per` VARCHAR(200) NULL,
  `tifam_per` VARCHAR(45) NULL,
  `tibom_per` VARCHAR(45) NULL,
  `seria_per` VARCHAR(45) NULL,
  `usuar_per` VARCHAR(45) NULL,
  `contr_per` VARCHAR(45) NULL,
  `statu_per` CHAR(1) NULL,
  `ident_tip` INT NOT NULL,
  `ident_fam` INT NOT NULL,
  PRIMARY KEY (`ident_per`),
  INDEX `fk_tab_per_tab_tip1_idx` (`ident_tip` ASC),
  INDEX `fk_tab_per_tab_fam1_idx` (`ident_fam` ASC),
  CONSTRAINT `fk_tab_per_tab_tip1`
    FOREIGN KEY (`ident_tip`)
    REFERENCES `ccambpla`.`tab_tip` (`ident_tip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_per_tab_fam1`
    FOREIGN KEY (`ident_fam`)
    REFERENCES `ccambpla`.`tab_fam` (`ident_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_not`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_not` (
  `ident_not` INT NOT NULL AUTO_INCREMENT,
  `titul_not` VARCHAR(45) NULL,
  `desco_not` VARCHAR(45) NULL,
  `descr_not` VARCHAR(2000) NULL,
  `image_not` VARCHAR(250) NULL,
  `fecpu_not` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `statu_not` VARCHAR(45) NULL,
  PRIMARY KEY (`ident_not`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_ref` (
  `ident_ref` INT NOT NULL AUTO_INCREMENT,
  `banco_ref` VARCHAR(45) NULL,
  `monto_ref` FLOAT NULL,
  PRIMARY KEY (`ident_ref`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccambpla`.`tab_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccambpla`.`tab_reg` (
  `ident_reg` INT NOT NULL,
  `nombr_reg` VARCHAR(45) NULL,
  `descr_reg` VARCHAR(250) NULL,
  `fecre_reg` DATE NULL,
  `statu_reg` CHAR(1) NULL,
  `ident_ref` INT NOT NULL,
  `ident_fam` INT NOT NULL,
  PRIMARY KEY (`ident_reg`),
  INDEX `fk_tab_ref1_idx` (`ident_ref` ASC),
  INDEX `fk_tab_reg_tab_fam1_idx` (`ident_fam` ASC),
  CONSTRAINT `fk_tab_ref1`
    FOREIGN KEY (`ident_ref`)
    REFERENCES `ccambpla`.`tab_ref` (`ident_ref`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_reg_tab_fam1`
    FOREIGN KEY (`ident_fam`)
    REFERENCES `ccambpla`.`tab_fam` (`ident_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ccambpla`.`tab_tip`
-- -----------------------------------------------------
START TRANSACTION;
USE `ccambpla`;
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (1, 'ADMINISTRADOR');
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (2, 'VOCERO');
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (3, 'JEFE DE CALLE');
INSERT INTO `ccambpla`.`tab_tip` (`ident_tip`, `nombr_tip`) VALUES (4, 'CIUDADANO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ccambpla`.`tab_fam`
-- -----------------------------------------------------
START TRANSACTION;
USE `ccambpla`;
INSERT INTO `ccambpla`.`tab_fam` (`ident_fam`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ccambpla`.`tab_per`
-- -----------------------------------------------------
START TRANSACTION;
USE `ccambpla`;
INSERT INTO `ccambpla`.`tab_per` (`ident_per`, `cedul_per`, `nombr_per`, `apeli_per`, `fecna_per`, `telem_per`, `telec_per`, `email_per`, `direc_per`, `tifam_per`, `tibom_per`, `seria_per`, `usuar_per`, `contr_per`, `statu_per`, `ident_tip`, `ident_fam`) VALUES (1, 26607655, 'CARLOS', 'GUANIPA', '1998-03-29', '(0426) 690 8396', '(0276) 353 2978', 'AGUSTINGUANIPA98@GMAIL.COM', 'PUEBLO NUEVO CALLE 2 BELLAVISTA RESD MILDREY PISO 7 APTO 74', 'HIJO/HIJA', 'GRANEL', '0123456', 'GUANIPA', 'GUANIPA', '1', 1, 1);

COMMIT;

